<?php


namespace Nemundo\Process\Group\Com\Table;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Parameter\GroupParameter;
use Nemundo\Process\Group\Site\GroupSite;
use Nemundo\Process\Group\Type\AbstractGroupContentType;
use Nemundo\Web\Site\Site;

class GroupTable extends AdminClickableTable
{

    /**
     * @var AbstractGroupContentType
     */
    public $groupContentType;

    public function getContent()
    {

        $header=new TableHeader($this);
        $header->addText('Group');


        $groupReader=new GroupReader();
        $groupReader->model->loadGroupType();

        if ($this->groupContentType !==null) {
            $groupReader->filter->andEqual($groupReader->model->groupTypeId, $this->groupContentType->typeId);
        }


        $groupReader->addOrder($groupReader->model->group);
        foreach ($groupReader->getData() as $groupRow) {
            $row=new BootstrapClickableTableRow($this);
            $row->addText($groupRow->group);
            $row->addText($groupRow->groupType->contentType);

            $site =new Site();  // clone(GroupSite::$site);
            $site->addParameter(new GroupParameter($groupRow->id));
            $row->addClickableSite($site);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}