<?php


namespace Nemundo\Process\Group\Com\Table;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Core\Language\LanguageCode;
use Nemundo\Html\Table\Th;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;
use Nemundo\Process\Group\Parameter\GroupUserParameter;
use Nemundo\Process\Group\Site\GroupUserDeleteSite;

class GroupUserTable extends AdminTable
{

    public $groupId;

    public function getContent()
    {

        $header = new TableHeader($this);
        //$header->addText('User');

        $th = new Th($header);
        $th->content[LanguageCode::EN] = 'User';
        $th->content[LanguageCode::DE] = 'Benutzer';

        $header->addEmpty();

        $groupReader = new GroupUserReader();
        $groupReader->model->loadUser();
        $groupReader->filter->andEqual($groupReader->model->groupId, $this->groupId);
        $groupReader->addOrder($groupReader->model->user->displayName);
        foreach ($groupReader->getData() as $groupUserRow) {
            $row = new TableRow($this);
            $row->addText($groupUserRow->user->displayName);

            $site = clone(GroupUserDeleteSite::$site);
            $site->addParameter(new GroupUserParameter($groupUserRow->id));
            //$site->addParameter(new GroupParameter($groupUserRow->groupId));
            //$site->addParameter(new UserParameter($groupUserRow->userId));
            $row->addIconSite($site);


        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}