<?php


namespace Nemundo\Process\Group\Com\Table;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;
use Nemundo\Process\Group\Parameter\GroupParameter;
use Nemundo\Process\Group\Parameter\GroupUserParameter;
use Nemundo\Process\Group\Site\GroupUserDeleteSite;
use Nemundo\User\Parameter\UserParameter;

class GroupUserTable extends AdminTable
{

    public $groupId;

    public function getContent()
    {

        $header=new TableHeader($this);
        $header->addText('User');
        $header->addEmpty();

        $groupReader = new GroupUserReader();
        $groupReader->model->loadUser();
        $groupReader->filter->andEqual($groupReader->model->groupId,$this->groupId );
        $groupReader->addOrder($groupReader->model->user->displayName);
        foreach ($groupReader->getData() as $groupUserRow) {
            $row = new TableRow($this);
            $row->addText($groupUserRow->user->displayName);

            $site = clone(GroupUserDeleteSite::$site);
            $site->addParameter(new GroupUserParameter($groupUserRow->id));
            //$site->addParameter(new GroupParameter($groupUserRow->groupId));
            //$site->addParameter(new UserParameter($groupUserRow->userId));
            $row->addIconSite($site);


        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}