<?php


namespace Nemundo\Process\Group\Com\Table;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;

class GroupUserTable extends AdminTable
{

    public $groupId;

    public function getContent()
    {

        $header=new TableHeader($this);
        $header->addText('User');
        $header->addEmpty();

        $groupReader = new GroupUserReader();
        $groupReader->model->loadUser();
        $groupReader->filter->andEqual($groupReader->model->groupId,$this->groupId );
        $groupReader->addOrder($groupReader->model->user->displayName);
        foreach ($groupReader->getData() as $groupUserRow) {
            $row = new TableRow($this);
            $row->addText($groupUserRow->user->displayName);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}