<?php


namespace Nemundo\Process\Group\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Data\GroupType\GroupTypeReader;
use Nemundo\Process\Group\Parameter\GroupParameter;


class AllGroupListBox extends BootstrapListBox
{

    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->label = 'Group';
        $this->name = (new GroupParameter())->getParameterName();
        //$listbox->submitOnChange = true;
        //$listbox->searchItem = true;
        //$listbox->emptyValueAsDefault=false;


    }


    public function getContent()
    {

        $groupTypeReader = new GroupTypeReader();
        $groupTypeReader->model->loadGroupType();
        $groupTypeReader->addOrder($groupTypeReader->model->groupType->contentType);
        foreach ($groupTypeReader->getData() as $groupTypeRow) {

            $this->addItemTitle($groupTypeRow->groupType->contentType);

            $reader = new GroupReader();
            $reader->filter->andEqual($reader->model->groupTypeId, $groupTypeRow->groupTypeId);
            $reader->addOrder($reader->model->group);
            foreach ($reader->getData() as $groupRow) {
                $this->addItem($groupRow->id, $groupRow->group);
            }

        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}