<?php


namespace Nemundo\Process\Group\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;
use Nemundo\Process\Group\Parameter\GroupParameter;


class GroupUserListBox extends BootstrapListBox
{

    public $groupType;

    //private $groupTypeList=[];

    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->label='Group';

        //$this->name = (new GroupParameter())->getParameterName();
        //$listbox->submitOnChange = true;
        //$listbox->searchItem = true;
        //$listbox->emptyValueAsDefault=false;


    }


    public function getContent()
    {

        $reader = new GroupUserReader();
        $reader->model->loadUser();
        //$reader->addOrder($reader->model->group);
        foreach ($reader->getData() as $groupRow) {
            $this->addItem($groupRow->id, $groupRow->user->displayName);
        }

        return parent::getContent();

    }

}