<?php


namespace Nemundo\Process\Group\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Group\Data\GroupType\GroupTypeReader;

class GroupTypeListBox extends BootstrapListBox
{

    public function getContent()
    {

        $this->label='Group Type';

        $reader=new GroupTypeReader();
        foreach ($reader->getData() as $groupTypeRow) {
            $this->addItem($groupTypeRow->id,$groupTypeRow->groupType);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}