<?php


namespace Nemundo\Process\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Data\Process\ProcessReader;

class ProcessListBox extends BootstrapListBox
{

    public function getContent()
    {

        $reader = new ProcessReader();
        foreach ($reader->getData() as $processRow) {
            $this->addItem($processRow->id,$processRow->process);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}