<?php


namespace Nemundo\Process\Com\Dropdown;


use Nemundo\Com\FormBuilder\RedirectTrait;
use Nemundo\Package\Bootstrap\Dropdown\BootstrapSiteDropdown;
use Nemundo\Process\Content\AbstractContentType;
use Nemundo\Process\Parameter\ContentTypeParameter;
use Nemundo\Process\Parameter\StatusParameter;
use Nemundo\Process\Status\AbstractStatus;
use Nemundo\Web\Site\AbstractSite;

class ContentTypeDropdown extends BootstrapSiteDropdown
{

    /**
     * @var AbstractSite
     */
    public $redirectSite;

    /**
     * @var AbstractContentType[]
     */
    public $contentTypeList=[];


    public function addContentType(AbstractContentType $contentType) {

        $this->contentTypeList[]=$contentType;
        return $this;


    }


    public function getContent()
    {

        foreach ($this->contentTypeList as $contentType) {

            $site = clone($this->redirectSite);
            $site->addParameter(new ContentTypeParameter($contentType->id));
            $site->title = $contentType->getClassNameWithoutNamespace();  //status->label;
            $this->addSite($site);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}