<?php


namespace Nemundo\Process\Com\Dropdown;


use Nemundo\Com\FormBuilder\RedirectTrait;
use Nemundo\Package\Bootstrap\Dropdown\BootstrapSiteDropdown;
use Nemundo\Process\Parameter\StatusParameter;
use Nemundo\Process\Status\AbstractStatus;
use Nemundo\Web\Site\AbstractSite;

class MenuStatusDropdown extends BootstrapSiteDropdown
{

    /**
     * @var AbstractSite
     */
    public $redirectSite;

    /**
     * @var AbstractStatus
     */
    public $status;


    public function getContent()
    {

        foreach ($this->status->getMenuStatus() as $status) {

            $site = clone($this->redirectSite);
            $site->addParameter(new StatusParameter($status->id));
            $site->title = $status->label;
            $this->addSite($site);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}