<?php


namespace Nemundo\Process\View;


use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Status\AbstractStatus;


// AbstractProcessStatusView
abstract class AbstractStatusView extends AbstractContentView  //HtmlContainer
{




    // parentId --> Problem da DocumentStatus etc.

    /**
     * @var string
     */
    public $workflowId;

    /**
     * @var AbstractStatus
     */
   // protected $status;

    /**
     * @var string
     */
   // public $dataId;



    public function getContent()
    {

        $p = new Paragraph($this);
        $p->content = 'Status View';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}