<?php

namespace Nemundo\Process\App\Assignment\Content;


use Nemundo\Core\Type\DateTime\Date;
use Nemundo\Package\Bootstrap\FormElement\BootstrapDatePicker;
use Nemundo\Process\Group\Com\GroupListBox;
use Nemundo\Process\Group\Com\ListBox\GroupTypeListBox;
use Nemundo\Process\Workflow\Content\Form\AbstractStatusForm;

abstract class AbstractAssignmentContentForm extends AbstractStatusForm
{

    /**
     * @var GroupTypeListBox
     */
    private $groupType;

    /**
     * @var GroupListBox
     */
    protected $group;

    /**
     * @var BootstrapDatePicker
     */
    protected $deadline;

    public function getContent()
    {

        //$this->groupType = new GroupTypeListBox($this);

        $this->group = new GroupListBox($this);
        $this->group->validation = true;

        $this->deadline = new BootstrapDatePicker($this);
        $this->deadline->label = 'Datum';
        $this->deadline->value = (new Date())->setNow()->getShortDateLeadingZeroFormat();
        //$this->datum->validation = true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    /*
    protected function onSubmit()
    {

        $status = new GroupAssignmentContentType();  // new GroupAssignmentContentType();
        $status->parentId = $this->parentId;
        $status->groupId = $this->group->getValue();
        $status->deadline->fromGermanFormat($this->deadline->getValue());
        $status->message = 'da muesch öbis mache ...';
        $status->saveType();

    }*/


}