<?php


namespace Nemundo\Process\App\Assignment\Content;


use Nemundo\Process\App\Notification\Category\TaskCategory;
use Nemundo\Process\Text\BoldText;
use Nemundo\Process\Workflow\Content\Status\AbstractProcessStatus;

class AssignmentProcessStatus extends AbstractAssignmentProcessStatus
{

    protected function loadContentType()
    {

        $this->typeLabel = 'Assignment';
        $this->typeId='f3122812-2cad-4c20-8b20-b26c5c2f23ba';
        $this->formClass=AssignmentProcessForm::class;


        // TODO: Implement loadContentType() method.
    }



    protected function onCreate()
    {

        $this->saveAssignment();

        $process = $this->getParentProcess();
        $process->changeAssignment($this->groupId);
        $process->changeDeadline($this->deadline);

    }


    protected function onFinished()
    {
        parent::onFinished(); // TODO: Change the autogenerated stub

        $this->sendGroupNotification($this->groupId, new TaskCategory());

    }


    public function getSubject()
    {

        return $this->getParentProcess()->getSubject();

    }


    public function getMessage()
    {

        $assignmentRow = $this->getDataRow();
        $subject = 'Zuweisung an ' . (new BoldText())->getBold($assignmentRow->assignment->group);

        return $subject;

    }


}