<?php


namespace Nemundo\Process\App\Survey\Content\Answer;


use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

class AnswerForm extends AbstractContentForm
{

    /**
     * @var BootstrapTextBox
     */
    private $answer;

    public function getContent()
    {

        $this->answer = new BootstrapTextBox($this);
        $this->answer->label='Answer';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {



        // TODO: Implement onSubmit() method.
    }

}