<?php


namespace Nemundo\Process\Workflow\Parameter;


use Nemundo\Process\Content\Data\Content\ContentReader;
use Nemundo\Process\Content\Parameter\AbstractContentUrlParameter;
use Nemundo\Process\Workflow\Content\Process\AbstractProcess;
use Nemundo\Process\Workflow\Data\Workflow\WorkflowReader;
use Nemundo\Web\Parameter\AbstractUrlParameter;

class WorkflowParameter extends AbstractUrlParameter  // AbstractContentUrlParameter
{

    protected function loadParameter()
    {
        $this->parameterName = 'workflow';
    }


    /**
     * @return AbstractProcess
     */
   /* public function getContentType()
    {
        return parent::getContentType(); // TODO: Change the autogenerated stub
    }*/


    /**
     * @return AbstractProcess
     */
    public function getProcess() {


        $reader = new WorkflowReader();
        $reader->model->loadContent();
        $reader->model->content->loadContentType();
        $workflowRow = $reader->getRowById($this->getValue());

        $process=$workflowRow->content->getContentType();

        return $process;


        /*
        $reader = new ContentReader();
        $reader->model->loadContentType();
        $contentRow = $reader->getRowById($this->getValue());
        $contentType = $contentRow->getContentType();
*/

    }


}