<?php


namespace Nemundo\Process\App\Survey\Content\Survey;


use Nemundo\Admin\Com\Title\AdminTitle;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Content\Com\Table\ContentLogTable;
use Nemundo\Process\Content\View\AbstractContentView;

class SurveyContentView extends AbstractContentView
{

    /**
     * @var SurveyContentType
     */
    public $contentType;

    public function getContent()
    {

        $surveyRow=$this->contentType->getDataRow();

        $title = new AdminTitle($this);
        $title->content = 'Survey';

        $p=new Paragraph($this);
        $p->content=$surveyRow->question;



        // save



        $table = new ContentLogTable($this);
        $table->contentType = $this->contentType;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}