<?php


namespace Nemundo\Process\App\News\Type;


use Nemundo\Process\App\News\Com\NewsContentForm;
use Nemundo\Process\App\News\Com\NewsContentView;
use Nemundo\Process\App\News\Data\News\News;
use Nemundo\Process\App\News\Data\News\NewsDelete;
use Nemundo\Process\App\News\Data\News\NewsReader;
use Nemundo\Process\Content\Type\AbstractContentType;

class NewsContentType extends AbstractContentType
{

    protected function loadContentType()
    {

        $this->typeId = '4adb432d-f02a-476f-abaf-1eb17390726f';

        $this->viewClass = NewsContentView::class;
        $this->formClass = NewsContentForm::class;

    }


    public $title;

    public $teaser;


    protected function onCreate()
    {

        $data = new News();
        $data->updateOnDuplicate = true;
        $data->id = $this->dataId;
        $data->title = $this->title;
        $data->teaser = $this->teaser;
        $data->save();

    }


    public function getSubject()
    {

        $row = (new NewsReader())->getRowById($this->dataId);
        $subject = $row->title;

//$subject='dataid'.$this->dataId;

        return $subject;

    }


    public function deleteType()
    {

        parent::deleteType(); // TODO: Change the autogenerated stub

        (new NewsDelete())->deleteById($this->dataId);

    }


}