<?php


namespace Nemundo\Process\App\News\Type;


use Nemundo\Process\Status\ProcessStatusTrait;

class NewsProcessStatus extends NewsContentType
{

    use ProcessStatusTrait;


    protected function loadContentType()
    {
        parent::loadContentType(); // TODO: Change the autogenerated stub

    $this->label = 'News';

    }


}