<?php


namespace Nemundo\Process\App\News\Type;


use Nemundo\Process\Workflow\Content\Status\ProcessStatusTrait;

class NewsProcessStatus extends NewsContentType
{

    use ProcessStatusTrait;

    //use Proce \Nemundo\Process\Workflow\Content\Status\ProcessStatusTrait ProcessStatusTrait;


    protected function loadContentType()
    {
        parent::loadContentType(); // TODO: Change the autogenerated stub

        $this->contentLabel = 'News';

    }


}