<?php


namespace Nemundo\Process\Template\Status;


use Nemundo\Core\Language\LanguageCode;
use Nemundo\Process\Template\Form\CancelStatusForm;
use Nemundo\Process\Template\View\CommentView;
use Nemundo\Process\Workflow\Content\Status\AbstractProcessStatus;
use Nemundo\User\Usergroup\AbstractUsergroup;

class AbstractCancelStatus extends AbstractProcessStatus
{


    public function __construct()
    {


        $this->label[LanguageCode::EN] = 'Cancel';
        $this->label[LanguageCode::DE] = 'Abbruch';

        //$this->id='510c9d20-74cc-43b6-82d3-d6a6df487813';

        $this->changeStatus=true;
        $this->closeWorkflow=true;
        parent::__construct();

        $this->viewClass = CommentView::class;

    }

  /*  protected function loadContentType()
    {
        //parent::loadContentType(); // TODO: Change the autogenerated stub




        //$this->formClass = CancelStatusForm::class;


    }*/

}