<?php


namespace Nemundo\Process\Template\Status;


class CancelStatus extends CommentStatus
{

    protected function loadStatus()
    {
        parent::loadStatus(); // TODO: Change the autogenerated stub

        $this->label='Cancel';
        $this->changeStatus=true;
        $this->id='510c9d20-74cc-43b6-82d3-d6a6df487813';

    }

}