<?php


namespace Nemundo\Process\Template\Status;


use Nemundo\Process\Workflow\Content\Status\AbstractStatus;
use Nemundo\Process\Template\Form\DeadlineChangeForm;

class DeadlineChangeStatus extends AbstractStatus
{

    protected function loadContentType()
    {
   $this->label='Deadline Change';
   $this->id='cd3ade01-3ef1-452f-8a45-dce792547220';
   $this->formClass=DeadlineChangeForm::class;
    }

    public function getLogText($dataId)
    {
        return parent::getSubject($dataId); // TODO: Change the autogenerated stub
    }

}