<?php


namespace Nemundo\Process\App\Assignment\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\App\Assignment\Data\AssignmentStatus\AssignmentStatusReader;

class AssignmentStatusListBox extends BootstrapListBox
{

    public function getContent()
    {

        $this->label='Assignment Status';

        $reader = new AssignmentStatusReader();
        foreach ($reader->getData() as $statusRow) {
            $this->addItem($statusRow->id,$statusRow->status);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}