<?php


namespace Nemundo\Process\Group\Com;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Parameter\GroupParameter;

class GroupListBox extends BootstrapListBox
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->name = (new GroupParameter())->getParameterName();
        //$listbox->submitOnChange = true;
        //$listbox->searchItem = true;
        //$listbox->emptyValueAsDefault=false;
        $reader = new GroupReader();
        foreach ($reader->getData() as $groupRow) {
            $this->addItem($groupRow->id, $groupRow->group);
        }


    }

}