<?php


namespace Nemundo\Process\Group\Com;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Parameter\GroupParameter;
use Schleuniger\App\Org\Content\Mitarbeiter\MitarbeiterContentType;

class GroupListBox extends BootstrapListBox
{

    private $groupTypeList=[];

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub


        $this->label='Group';
        $this->name = (new GroupParameter())->getParameterName();
        //$listbox->submitOnChange = true;
        //$listbox->searchItem = true;
        //$listbox->emptyValueAsDefault=false;


    }


    public function getContent()
    {

        $reader = new GroupReader();
        $reader->filter->andEqual($reader->model->groupTypeId, (new MitarbeiterContentType())->contentId);
        foreach ($reader->getData() as $groupRow) {
            $this->addItem($groupRow->id, $groupRow->group);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}