<?php


namespace Nemundo\Process\Group\Com;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Process\Content\Com\Container\AbstractParentContainer;
use Nemundo\Process\Content\Data\ContentGroup\ContentGroupReader;
use Nemundo\Process\Group\Content\GroupContentView;

class GroupParentContainer extends AbstractParentContainer
{
    public function getContent()
    {

      $table = new AdminTable($this);

      $header=new TableHeader($table);
      $header->addText('Visible for');

        $reader = new ContentGroupReader();
        $reader->model->loadGroup();
        $reader->filter->andEqual($reader->model->contentId,$this->parentId);
        foreach ($reader->getData() as $contentGroupRow) {
            $row=new TableRow($table);
            $row->addText($contentGroupRow->group->group);

            $view = new GroupContentView($row);
            $view->dataId=$contentGroupRow->groupId;

        }



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}