<?php


namespace Nemundo\Process\Store;


class ShopDescriptionStore extends AbstractLargeTextStore
{

    protected function loadStore()
    {
        $this->dataId = 'shop2';
        //parent::loadStore(); // TODO: Change the autogenerated stub
    }

}