<?php


namespace Nemundo\Process\App\Podcast\Scheduler;


use Nemundo\App\Scheduler\Job\AbstractScheduler;
use Nemundo\Core\Debug\Debug;
use Nemundo\Process\App\Podcast\Data\Feed\FeedReader;

class PodcastScheduler extends AbstractScheduler
{

    protected function loadScript()
    {
        parent::loadScript(); // TODO: Change the autogenerated stub

        $this->consoleScript=true;
        $this->scriptName='podcast-import';

    }


    public function run()
    {
        // TODO: Implement run() method.

        $reader = new FeedReader();
        foreach ($reader->getData() as $feedRow) {


            (new Debug())->write($feedRow->rssUrl);


        }


    }

}