<?php


namespace Nemundo\Process\Template\Content\MultiFile;


use Nemundo\Admin\Com\Title\AdminSubtitle;
use Nemundo\Com\Html\Hyperlink\UrlHyperlink;
use Nemundo\Com\Html\Listing\UnorderedList;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Template\Data\TemplateMultiFile\TemplateMultiFileReader;

class MultiFileContentView extends AbstractContentView
{

    public function getContent()
    {

        $title = new AdminSubtitle($this);
        $title->content = 'Multi File: '.$this->contentType->getContentId();


        $reader = new TemplateMultiFileReader();// new MultiDocumentAnforderungReader();
        //$reader->model->document->file->redirectSite = ProzesssteuerungConfig::$site->multiDocumentAnforderungRedirect;
        $reader->filter->andEqual($reader->model->dataContentId, $this->contentType->getContentId());
        //$reader->filter->andEqual($reader->model->status, true);

        $list = new UnorderedList($this);
        $list->addCssClass('list-unstyled');

        foreach ($reader->getData() as $row) {

            $list->addText($row->file->getFilename().$row->dataContentId);

            /*$link = new UrlHyperlink($list);
            $link->url = $row->document->getUrl();
            $link->content = $row->document->getFilename();*/
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}