<?php


namespace Nemundo\Process\App\Wiki\Content;


use Nemundo\Core\Debug\Debug;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\App\Wiki\Parameter\WikiParameter;
use Nemundo\Process\Content\Form\AbstractContentForm;

class WikiPageContentForm extends AbstractContentForm
{

    /**
     * @var WikiPageContentType
     */
    public $contentType;

    /**
     * @var BootstrapTextBox
     */
    private $pageTitle;

    public function getContent()
    {

        //$p=new Paragraph($this);
        //$p->content='dataid: '.$this->dataId;

        $this->pageTitle = new BootstrapTextBox($this);
        $this->pageTitle->label = 'Wiki Title';
        $this->pageTitle->validation = true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $wikiRow = $this->contentType->getDataRow();
        $this->pageTitle->value= $wikiRow->title;

    }

    protected function onSubmit()
    {

        //(new Debug())->write($this->dataId);

        $type = new WikiPageContentType($this->dataId);
        $type->parentId=$this->parentId;
        $type->title = $this->pageTitle->getValue();
        $type->saveType();

        if ($this->appendParameter) {
            $this->redirectSite->addParameter(new WikiParameter($type->getDataId()));
        }

    }

}