<?php


namespace Nemundo\Process\App\Wiki\Content;


use Nemundo\Com\FormBuilder\AbstractFormBuilder;
use Nemundo\Html\Form\Input\TextInput;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;

class WikiHtmlForm extends AbstractFormBuilder
{

    /**
     * @var BootstrapTextBox
     */
    private $wikiTitle;

    public function getContent()
    {

        $this->wikiTitle=new BootstrapTextBox($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.




    }

}