<?php


namespace Nemundo\Process\Template\Content\VersionText;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Admin\Com\Table\AdminTableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Template\Content\Text\TextContentForm;
use Nemundo\Process\Template\Content\Text\TextContentType;

class VersionTextContentForm extends AbstractContentForm
{


    /**
     * @var BootstrapTextBox
     */
    private $text;

    public function getContent()
    {

        $this->text=new BootstrapTextBox($this);
        $this->text->label='Version Text';




        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $type=new VersionTextContentType($this->dataId);

        //$p = new Paragraph($this);
        //$p->content = $type->getDataRow()->text;

        $this->text->value=$type->getDataRow()->text;


        $table = new AdminTable($this);

        $header=new AdminTableHeader($table);
        $header->addText('Text');
        $header->addText('Version');



        foreach ($type->getChild() as $customRow) {

          $versionContentType =   $customRow->getContentType();

          $row=new TableRow($table);
          $row->addText($versionContentType->getSubject());
          $row->addText($customRow->itemOrder);


        }





    }

    protected function onSubmit()
    {

        //$type=new VersionTextContentType($this->dataId);

        $this->contentType->parentId=$this->parentId;
        $this->contentType->text=$this->text->getValue();
        $this->contentType->saveType();

        // TODO: Implement onSubmit() method.
    }

}