<?php


namespace Nemundo\Process\Template\Content\VersionText;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Template\Content\Text\TextContentForm;
use Nemundo\Process\Template\Content\Text\TextContentType;

class VersionTextContentForm extends AbstractContentForm
{


    /**
     * @var BootstrapTextBox
     */
    private $text;

    public function getContent()
    {

        $this->text=new BootstrapTextBox($this);
        $this->text->label='Version Text';




        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $table = new AdminTable($this);

        $header=new TableHeader($table);
        $header->addText('Text');
        $header->addText('Version');


        $type=new VersionTextContentType($this->dataId);
        foreach ($type->getChild() as $customRow) {

          $versionContentType =   $customRow->getContentType();

          $row=new TableRow($table);
          $row->addText($versionContentType->getSubject());
          //$row->addText($customRow->)


        }





    }

    protected function onSubmit()
    {

        $type=new VersionTextContentType($this->dataId);
        $type->parentId=$this->parentId;
        $type->text=$this->text->getValue();
        $type->saveType();

        // TODO: Implement onSubmit() method.
    }

}