<?php


namespace Nemundo\Process\Group\Content;


use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Group\Content\Group\GroupContentType;


class GroupContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapTextBox
     */
    private $group;

    public function getContent()
    {

        $this->group=new BootstrapTextBox($this);
        $this->group->label='Group';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $item=new GroupContentType($this->dataId);  // GroupContentItem();
        $item->group = $this->group->getValue();
        $item->saveItem();

    }

}