<?php


namespace Nemundo\Process\Group\Content;


use Nemundo\Admin\Com\Title\AdminSubtitle;
use Nemundo\Com\Html\Listing\UnorderedList;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Group\Data\Group\GroupReader;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;

class GroupContentView extends AbstractContentView
{
    public function getContent()
    {
        $groupRow=(new GroupReader())->getRowById($this->dataId);

        $p=new Paragraph($this);
        $p->content=$groupRow->group.' ('.$this->contentType->typeLabel.')';


        $subtitle=new AdminSubtitle($this);
        $subtitle->content='User';

        $ul=new UnorderedList($this);

        $reader=new GroupUserReader();
        $reader->model->loadUser();
        $reader->filter->andEqual($reader->model->groupId,$this->dataId);
        foreach ($reader->getData() as $groupUserRow) {
            $ul->addText($groupUserRow->user->displayName);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}