<?php


namespace Nemundo\Process\Content\Com\Form;


use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Process\Content\Data\ContentGroup\ContentGroup;
use Nemundo\Process\Group\Com\ListBox\AllGroupListBox;

class ContentGroupForm extends BootstrapForm
{

    public $contentId;

    /**
     * @var AllGroupListBox
     */
    private $group;

    public function getContent()
    {

        $this->group = new AllGroupListBox($this);
        $this->group->submitOnChange=true;

        $this->submitButton->visible=false;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $data = new ContentGroup();
        $data->ignoreIfExists=true;
        $data->contentId=$this->contentId;
        $data->groupId=$this->group->getValue();
        $data->save();

    }

}