<?php


namespace Nemundo\Process\Com\Button;


use Nemundo\Admin\Com\Button\AdminSiteButton;
use Nemundo\Process\Parameter\StatusParameter;
use Nemundo\Process\Status\AbstractStatus;

class NextStatusButton extends AdminSiteButton
{

    /**
     * @var AbstractStatus
     */
    public $status;

    public function getContent()
    {

        if ($this->status !== null) {
        $this->content = $this->status->label;
        $this->site->addParameter(new StatusParameter($this->status->id));
        } else {
            $this->disabled=true;
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}