<?php


namespace Nemundo\Process\App\Feed\Content\Item;


use Nemundo\Process\Content\View\AbstractContentView;

class FeedItemContentView extends AbstractContentView
{

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}