<?php


namespace Nemundo\Process\Template\Status\SubjectChange;


use Nemundo\Core\Language\LanguageCode;
use Nemundo\Core\Text\TextBold;
use Nemundo\Process\Template\Data\TemplateText\TemplateText;
use Nemundo\Process\Template\Data\TemplateText\TemplateTextReader;
use Nemundo\Process\Text\BoldText;
use Nemundo\Process\Workflow\Content\Status\AbstractProcessStatus;
use Nemundo\Process\Workflow\Data\Workflow\WorkflowUpdate;

class SubjectChangeProcessStatus extends AbstractProcessStatus
{

    public $subject;


    protected function loadContentType()
    {

        $this->typeLabel[LanguageCode::EN] = 'Subject Change';
        $this->typeLabel[LanguageCode::DE] = 'Betreff Ändern';


        $this->typeId = '54527fcb-d417-4bd4-acfe-53e5e689e3bb';

        $this->formClass = SubjectChangeStatusForm::class;

        // TODO: Implement loadContentType() method.
    }


    protected function onCreate()
    {

        $data = new TemplateText();
        $data->text = $this->subject;
        $this->dataId = $data->save();

        $workflowId = $this->getParentProcess()->getWorkflowId();

        $update = new WorkflowUpdate();
        $update->subject = $this->subject;
        $update->updateById($workflowId);

    }


    public function saveType()
    {


        $workflowRow = $this->getParentProcess()->getWorkflowRow();

        if ($workflowRow->subject !== $this->subject) {
            parent::saveType();
        }

        //return parent::saveType(); // TODO: Change the autogenerated stub
    }


    public function getDataRow()
    {

        parent::getDataRow(); // TODO: Change the autogenerated stub
    }

    public function getSubject()
    {


        $subject = 'Subject was changed to ' . (new BoldText())->getBold((new TemplateTextReader())->getRowById($this->dataId)->text);
        return $subject;

    }


}