<?php


namespace Nemundo\Process\Template\Content\User;


use Nemundo\Admin\Com\Table\AdminLabelValueTable;
use Nemundo\Com\Html\Listing\UnorderedList;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Group\Data\GroupUser\GroupUserReader;
use Nemundo\User\Data\User\UserReader;

class UserContentView extends AbstractContentView
{

    public function getContent()
    {

        $userRow=(new UserReader())->getRowById($this->dataId);

        $table= new AdminLabelValueTable($this);
        $table->addLabelValue('Login',$userRow->login);

        $ul=new UnorderedList($this);

        $reader = new GroupUserReader();
        $reader->model->loadGroup();
        $reader->filter->andEqual($reader->model->userId,$this->dataId);
        foreach ($reader->getData() as $groupUserRow) {
            $ul->addText($groupUserRow->group->group);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}