<?php


namespace Nemundo\Process\App\Notification\Com\HyperlinkList;


use Nemundo\Db\Sql\Field\CountField;
use Nemundo\Package\Bootstrap\Listing\BootstrapHyperlinkList;
use Nemundo\Process\App\Notification\Data\Notification\NotificationReader;
use Nemundo\Process\App\Notification\Filter\UserNotificationFilter;
use Nemundo\Process\App\Notification\Parameter\ArchiveParameter;
use Nemundo\Process\App\Notification\Site\UserNotificationSite;
use Nemundo\Process\Content\Parameter\ContentTypeParameter;
use Nemundo\Web\Site\AbstractSite;

class NotificationContentTypeHyperlinkList extends BootstrapHyperlinkList
{

    /**
     * @var AbstractSite
     */
    public $redirectSite;

    public function getContent()
    {


        $reader =new NotificationReader();
        $reader->model->loadContentType();
        $reader->filter=new UserNotificationFilter(false);
        $reader->addGroup($reader->model->contentTypeId);

        $countField = new CountField($reader);

        foreach ($reader->getData() as $notificationRow) {

            $count =$notificationRow->getModelValue($countField);

            $site =clone($this->redirectSite);  // clone(UserNotificationSite::$site);
            $site->addParameter(new ArchiveParameter());
            $site->addParameter(new ContentTypeParameter($notificationRow->contentTypeId));
            $site->title=$notificationRow->contentType->contentType.' ('.$count.')';
            $this->addSite($site);

        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}