<?php


namespace Nemundo\Process\Template\Content\Item;


use Nemundo\Process\Content\Type\AbstractTreeContentType;

class ActiveItemContentType extends AbstractTreeContentType
{

    protected function loadContentType()
    {

        $this->typeLabel='Activate Item';
        $this->typeId='61e7a40e-d049-4984-966f-35c761d983fd';

    }


    public function getSubject()
    {

        return parent::getSubject(); // TODO: Change the autogenerated stub
    }

}