<?php


namespace Nemundo\Process\Template\Content\Item;


use Nemundo\Process\Content\Type\AbstractTreeContentType;

class CreateItemContentType extends AbstractTreeContentType
{

    protected function loadContentType()
    {

        $this->typeLabel='Create Item';
        $this->typeId='6cf24cb3-18dd-41b6-9683-89550db978c1';

    }


    public function getSubject()
    {

        return parent::getSubject(); // TODO: Change the autogenerated stub
    }


    public function saveType()
    {
        parent::saveType(); // TODO: Change the autogenerated stub
    }

}