<?php


namespace Nemundo\Process\Template\Content\Item;


use Nemundo\Process\Content\Type\AbstractTreeContentType;

class EditItemContentType extends AbstractTreeContentType
{

    protected function loadContentType()
    {

        $this->typeLabel='Edit Item';
        $this->typeId='99b1c73e-3eeb-4c66-a657-42152f6d977f';

    }


    public function getSubject()
    {

        return parent::getSubject(); // TODO: Change the autogenerated stub
    }

}