<?php


namespace Nemundo\Process\Template\Content\Item;


use Nemundo\Process\Content\Type\AbstractTreeContentType;

class InactiveItemContentType extends AbstractTreeContentType
{

    protected function loadContentType()
    {

        $this->typeLabel='Inactive Item';
        $this->typeId='9c8588d6-d3c4-477d-a9db-5b0128928c43';

    }


    public function getSubject()
    {

        return parent::getSubject(); // TODO: Change the autogenerated stub
    }

}