<?php


namespace Nemundo\Process\App\Survey\Content\View;


use Nemundo\Admin\Com\Table\AdminLabelValueTable;
use Nemundo\Com\Html\Listing\UnorderedList;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\App\Survey\Content\Type\SurveyContentType;
use Nemundo\Process\App\Survey\Data\Survey\SurveyReader;
use Nemundo\Process\Content\Data\ContentStatus\ContentStatusReader;
use Nemundo\Process\Content\View\AbstractContentView;

class SurveyContentView extends AbstractContentView
{

    public function getContent()
    {

        $surveyRow = (new SurveyReader())->getRowById($this->dataId);

        $table = new AdminLabelValueTable($this);
        $table->addLabelValue('Vorname',$surveyRow->vorname);

        /*
        $contentStatusReader=new ContentStatusReader();
        $contentStatusReader->model->loadStatus();
        $contentStatusReader->filter->andEqual($contentStatusReader->model->contentId,$this->dataId);
        $contentStatusRow =$contentStatusReader->getRow();

        $table->addLabelValue('Status Content Type',$contentStatusRow->status->contentType);*/


        $surveyType=new SurveyContentType($this->dataId);

        $status =$surveyType->getStatus();  // $contentStatusRow->status->getContentType();

        $table->addLabelValue('Status Content Type',$status->typeLabel);


        $ul = new UnorderedList($this);
        foreach ($status->getMenuList() as $menu) {
            $ul->addText($menu->typeLabel);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub

    }

}