<?php


namespace Nemundo\Process\App\Message\Content;


use Nemundo\Admin\Com\Title\AdminSubtitle;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\App\Message\Data\Message\MessageReader;
use Nemundo\Process\App\Message\Data\MessageTo\MessageToReader;
use Nemundo\Process\Content\View\AbstractContentView;

class MessageContentView extends AbstractContentView
{

    public function getContent()
    {

        $messageRow = (new MessageReader())->getRowById($this->dataId);

        $toReader = new MessageToReader();
        $toReader->model->loadTo();
        $toReader->filter->andEqual($toReader->model->messageId, $messageRow->id);
        foreach ($toReader->getData() as $toRow) {
            $p = new Paragraph($this);
            $p->content = 'To: ' . $toRow->to->group;
        }

        $subtitle = new AdminSubtitle($this);
        $subtitle->content = $messageRow->subject;

        $p = new Paragraph($this);
        $p->content = $messageRow->message;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}