<?php


namespace Nemundo\Process\App\Feed\Site;


use Nemundo\Package\FontAwesome\Site\AbstractDeleteIconSite;
use Nemundo\Process\App\Feed\Content\Feed\FeedContentType;
use Nemundo\Process\App\Feed\Parameter\FeedParameter;
use Nemundo\Web\Url\UrlReferer;

class FeedDeleteSite extends AbstractDeleteIconSite
{

    /**
     * @var FeedDeleteSite
     */
    public static $site;

    protected function loadSite()
    {
        parent::loadSite(); // TODO: Change the autogenerated stub

        $this->url='feed-delete';

        FeedDeleteSite::$site=$this;

    }


    public function loadContent()
    {

        $feedId=(new FeedParameter())->getValue();
        (new FeedContentType($feedId))->deleteType();

        (new UrlReferer())->redirect();

    }

}