<?php


namespace Nemundo\Process\Com\Container;


use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Process\Data\WorkflowLog\WorkflowLogReader;

class WorkflowStreamContainer extends AbstractHtmlContainer
{

    public $workflowId;

    public function getContent()
    {

        $reader = new WorkflowLogReader();
        $reader->model->loadStatus();
        $reader->model->loadUser();// loadMitarbeiter();
        $reader->filter->andEqual($reader->model->workflowId, $this->workflowId);
        foreach ($reader->getData() as $logRow) {

            $status = $logRow->status->getStatus();


            $widget = new AdminWidget($this);
            $widget->widgetTitle =$status->label.' '.$logRow->user->login.' '.$logRow->dateTime->getShortDateTimeWithSecondLeadingZeroFormat();

            if ($status->hasView()) {

            $view = $status->getView($widget);
            $view->dataId = $logRow->dataId;

            }
            //$row->addText($status->getLogText($logRow->dataId));
        }

        return parent::getContent(); // TODO: Change the autogenerated stub

    }


}