<?php


namespace Nemundo\Process\View;


use Nemundo\Admin\Com\Widget\AbstractAdminWidget;
use Schleuniger\App\ChangeRequest\Com\Table\WorkflowLogTable;

class WorkflowLogView extends AbstractAdminWidget
{

    /**
     * @var string
     */
    public $workflowId;

    protected function loadWidget()
    {
        // TODO: Implement loadWidget() method.
    }


    public function getContent()
    {

        $this->widgetTitle='Workflow Log';

        $table = new WorkflowLogTable($this);
        $table->workflowId=$this->workflowId;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}