<?php


namespace Nemundo\Process\Template\View;


use Nemundo\Core\Type\Text\Html;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Template\Data\LargeText\LargeTextReader;
use Nemundo\Process\View\AbstractStatusView;

class CommentView extends AbstractStatusView
{

    public function getContent()
    {

        $row = (new LargeTextReader())->getRowById($this->dataId);

        $p = new Paragraph($this);
        $p->content = (new Html($row->largeText))->getValue();

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}