<?php


namespace Nemundo\Process\Template\View;


use Nemundo\Com\Html\Hyperlink\UrlHyperlink;
use Nemundo\Com\Video\YouTube\YouTubePlayer;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Template\Data\Youtube\YoutubeReader;

class YoutubeContentView extends AbstractContentView
{

    public function getContent()
    {

        $youtubeRow = (new YoutubeReader())->getRowById($this->dataId);

        $player=new YouTubePlayer($this);
        $player->videoId = $youtubeRow->youtubeId;
        $player->autoPlay=true;


        $hyperlink = new UrlHyperlink($this);
        $hyperlink->openNewWindow=true;
        $hyperlink->url = $youtubeRow->url;
        $hyperlink->content = $youtubeRow->url;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}