<?php


namespace Nemundo\Process\Template\Content\Event;


use Nemundo\Core\Type\DateTime\Date;
use Nemundo\Process\Content\Item\AbstractContentItem;
use Nemundo\Process\Template\Data\Event\Event;
use Nemundo\Process\Template\Data\Event\EventDelete;
use Nemundo\Process\Template\Data\Event\EventReader;

class EventContentItem extends AbstractContentItem
{

    /**
     * @var Date
     */
    public $date;

    public $event;


    protected function loadItem()
    {
        $this->contentType=new EventContentType();
        parent::loadItem(); // TODO: Change the autogenerated stub
    }

    protected function saveData()
    {
        // TODO: Implement saveData() method.



        $data = new Event();
        $data->id=$this->dataId;
        $data->date=$this->date;
        $data->event=$this->event;
        $data->save();

    }


    public function deleteItem()
    {

        parent::deleteItem(); // TODO: Change the autogenerated stub
        (new EventDelete())->deleteById($this->dataId);


    }


    public function getSubject()
    {

        $eventRow=(new EventReader())->getRowById($this->dataId);

        $subject=$eventRow->date->getShortDateLeadingZeroFormat().' '.$eventRow->event;
        return $subject;


    }

}