<?php


namespace Nemundo\Process\Template\Content\Event;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\Content\View\AbstractContentList;
use Nemundo\Process\Template\Data\Event\EventReader;

class EventContentList extends AbstractContentList
{

    public function getContent()
    {

        $table=new AdminClickableTable($this);

        $header= new TableHeader($table);
        $header->addText('Datum');
        $header->addText('Event');

        $reader = new EventReader();
        foreach ($reader->getData() as $eventRow) {

            $row= new BootstrapClickableTableRow($table);
            $row->addText($eventRow->date->getShortDateLeadingZeroFormat());
            $row->addText($eventRow->event);
            $row->addClickableSite($this->getRedirectSite($eventRow->id));



        }



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}