<?php


namespace Nemundo\Process\Template\Content\Event;


use Nemundo\Admin\Com\Button\AdminSiteButton;
use Nemundo\Admin\Com\Title\AdminSubtitle;
use Nemundo\Html\Block\Div;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Content\Item\ContentItem;
use Nemundo\Process\Content\Parameter\DataIdParameter;
use Nemundo\Process\Content\Site\ContentItemSite;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Template\Data\Event\EventReader;

class EventContentView extends AbstractContentView
{

    public function getContent()
    {

        $eventRow=(new EventReader())->getRowById($this->dataId);

        $subtitle=new AdminSubtitle($this);
        $subtitle->content=$eventRow->event;

        $p=new Paragraph($this);
        $p->content= $eventRow->date->getLongFormatWithWeekday();


        // sub image

        $contentItem = new ContentItem($this->dataId);

        foreach ($contentItem->getChild() as $contentRow) {

            $div = new Div($this);

            $contentRow->contentType->getContentType();

            $view = $contentRow->contentType->getContentType()->getView($div);
            $view->dataId = $contentRow->id;

        }



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}