<?php


namespace Nemundo\Process\App\Message\Notification;


use Nemundo\Process\App\Notification\Content\AbstractNotificationContentType;

class MessageNotification extends AbstractNotificationContentType
{

    protected function loadContentType()
    {

        $this->typeLabel='Message App Notification';
        $this->typeId='c8e95141-40ce-4849-a209-99b523ac8b5c';

    }


    public function getMessage()
    {

        return parent::getMessage(); // TODO: Change the autogenerated stub
    }


}