<?php


namespace Nemundo\Process\App\Notification\Content\Forward;


use Nemundo\Package\Bootstrap\Form\BootstrapForm;
use Nemundo\Process\App\Notification\Type\NotificationTrait;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Type\AbstractTreeContentType;
use Nemundo\User\Com\ListBox\UserListBox;

class ForwardContentForm extends BootstrapForm  // AbstractContentForm
{

    /**
     * @var AbstractTreeContentType|NotificationTrait
     */
    public $contentType;


    /**
     * @var UserListBox
     */
    private $user;

    public function getContent()
    {

        $this->user=new UserListBox($this);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.


        $this->contentType->sendUserNotification($this->user->getValue());




    }

}