<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

class DescriptionContentForm extends AbstractContentForm
{


    private $description;

    public function getContent()
    {

        $this->description=new BootstrapLargeTextBox($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.
    }

}