<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Html\Container\AbstractContentContainer;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Content\Form\AbstractContentActionPanel;
use Nemundo\Process\Content\Form\AbstractContentForm;

class OptionTextContentForm extends AbstractContentForm  // AbstractContentActionPanel
{


    public function getContent()
    {

        $p=new Paragraph($this);
        $p->content='Opteion TExt';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.
    }

}