<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Core\Random\UniqueId;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\App\Survey\Data\Survey\Survey;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Parameter\DataIdParameter;

class SurveyContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapTextBox
     */
    private $firstName;

    /**
     * @var BootstrapTextBox
     */
    private $lastName;

    public function getContent()
    {

        $this->firstName=new BootstrapTextBox($this);
        $this->firstName->label='First Name';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.


        $dataId = (new UniqueId())->getUniqueId();

        $data= new Survey();
        $data->id=$dataId;
        $data->vorname = $this->firstName->getValue();
        $data->save();

        $this->redirectSite->addParameter(new DataIdParameter($dataId));


    }

}