<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Process\App\Survey\Content\Type\SurveyContentType;
use Nemundo\Process\Content\Com\Container\AbstractSequenceContainer;

class SurveyContentContainer extends AbstractSequenceContainer
{
    public function getContent()
    {
        $this->contentType=new SurveyContentType();
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}