<?php


namespace Nemundo\Process\Content\Com\Dropdown;


use Nemundo\Package\Bootstrap\Dropdown\BootstrapSiteDropdown;
use Nemundo\Process\Content\Parameter\ContentTypeParameter;
use Nemundo\Process\Content\Type\AbstractContentType;
use Nemundo\Process\Content\Collection\AbstractContentTypeCollection;
use Nemundo\Process\Group\Check\GroupRestrictionTrait;
use Nemundo\Web\Site\AbstractSite;
use Nemundo\Web\Site\Site;

class ContentTypeCollectionDropdown extends BootstrapSiteDropdown
{

    use GroupRestrictionTrait;

    /**
     * @var AbstractSite
     */
    public $redirectSite;

    /**
     * @var AbstractContentTypeCollection
     */
    public $contentTypeCollection;


    public function getContent()
    {

        if ($this->redirectSite == null) {
            $this->redirectSite=new Site();
        }


        foreach ($this->contentTypeCollection->getContentTypeList() as $contentType) {

            $site = clone($this->redirectSite);
            $site->addParameter(new ContentTypeParameter($contentType->typeId));
            $site->title = $contentType->typeLabel;
            $this->addSite($site);

        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }




}