<?php


namespace Nemundo\Process\Template\Content\Number;


use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\Content\View\AbstractContentView;

class NumberContentView extends AbstractContentView
{
    /**
     * @var AbstractNumberContentType
     */
    public $contentType;

    public function getContent()
    {

        $textRow=$this->contentType->getDataRow();

        $p=new Paragraph($this);
        $p->content= 'number:'.$textRow->number;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}