<?php


namespace Nemundo\Process\Cms\Com\Dropdown;


use Nemundo\Package\Bootstrap\Dropdown\BootstrapSiteDropdown;
use Nemundo\Process\App\Wiki\Data\Wiki\WikiReader;
use Nemundo\Process\App\Wiki\Parameter\WikiParameter;
use Nemundo\Process\App\Wiki\Site\WikiAddSite;
use Nemundo\Process\Cms\Data\CmsType\CmsTypeReader;
use Nemundo\Process\Cms\Site\CmsEditorSite;
use Nemundo\Process\Content\Parameter\ContentTypeParameter;
use Nemundo\Process\Content\Parameter\DataParameter;
use Nemundo\Process\Content\Parameter\ParentParameter;
use Nemundo\Process\Content\Type\AbstractContentType;

class CmsAddDropdown extends BootstrapSiteDropdown
{

    //public $dataId;

    //public $parentId;

    /**
     * @var AbstractContentType
     */
    public $parentContentType;

    public function getContent()
    {

        $reader = new CmsTypeReader();
        $reader->model->loadCmsContentType();
        $reader->filter->andEqual($reader->model->parentContentTypeId,$this->parentContentType->typeId);

        foreach ($reader->getData() as $wikiRow) {
            $site=clone(CmsEditorSite::$site);
            $site->title=$wikiRow->cmsContentType->contentType;
            $site->addParameter(new ParentParameter($this->parentContentType->getContentId()));
            $site->addParameter(new ContentTypeParameter($wikiRow->cmsContentTypeId));
            //$site->addParameter(new Parent WikiParameter($wikiRow->id));
            //$site->addParameter(new DataParameter($this->dataId));
            $this->addSite($site);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}