<?php


namespace Nemundo\Process\App\Assignment\Content\ReAssignment;


use Nemundo\Process\Workflow\Content\Status\ProcessStatusTrait;

class ReAssignmentProcessStatus extends ReAssignmentContentType
{

    use ProcessStatusTrait;


    protected function loadContentType()
    {
        parent::loadContentType(); // TODO: Change the autogenerated stub

        $this->typeLabel = 'Re-Assignment (Status)';
        $this->typeId = '31c8838f-4e6a-488a-8d13-8f4bdceedee0';

    }

    protected function onCreate()
    {

        parent::onCreate(); // TODO: Change the autogenerated stub
        $this->getParentProcess()->changeAssignment($this->groupId);
        $this->getParentProcess()->changeDeadline($this->deadline);

    }

}