<?php


namespace Nemundo\Process\App\Notification\Com\Table;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Core\Language\LanguageCode;
use Nemundo\Db\Sql\Order\SortOrder;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Html\Table\Th;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\App\Notification\Data\Notification\NotificationPaginationReader;
use Nemundo\Process\App\Notification\Filter\UserNotificationFilter;
use Nemundo\Process\App\Notification\Parameter\NotificationParameter;
use Nemundo\Process\App\Notification\Site\ArchiveSite;
use Nemundo\Process\App\Notification\Site\RedirectSite;
use Nemundo\Process\Config\ProcessConfig;

class UserNotificationTable extends AbstractHtmlContainer
{

    public function getContent()
    {



        $table = new AdminClickableTable($this);

        $header = new TableHeader($table);

        $th = new Th($header);
        $th->content[LanguageCode::EN] = 'Subject';
        $th->content[LanguageCode::DE] = 'Betreff';

        $th = new Th($header);
        $th->content[LanguageCode::EN] = 'Message';
        $th->content[LanguageCode::DE] = 'Nachricht';

        $th = new Th($header);
        $th->content[LanguageCode::EN] = 'Date';
        $th->content[LanguageCode::DE] = 'Datum';


        //$header->addText('Archive');
       /* $header->addText('Notification Type');
        $header->addText('Subject');
        $header->addText('Message');
        $header->addText('Date/Time');*/
        //$header->addText('To');
        $header->addEmpty();


        $notificationReader = new NotificationPaginationReader();
        //$notificationReader->model->loadSubjectContent();
        //$notificationReader->model->subjectContent->loadContentType();
        $notificationReader->model->loadContent();
        $notificationReader->model->content->loadContentType();
        //$notificationReader->model->loadTo();

        $notificationReader->filter = new UserNotificationFilter();

        //$notificationReader->filter->andEqual($notificationReader->model->toId, (new UserSessionType())->userId);

        /*
        if ($listbox->hasValue()) {

        if ($listbox->getValue() =='0') {
               $notificationReader->filter->andEqual($notificationReader->model->archive,false);
        } else {
            $notificationReader->filter->andEqual($notificationReader->model->archive,true);
        }

        } else {

        }*/


        $notificationReader->addOrder($notificationReader->model->id, SortOrder::DESCENDING);
        $notificationReader->paginationLimit = ProcessConfig::PAGINATION_LIMIT;
        foreach ($notificationReader->getData() as $notificationRow) {

            $row = new BootstrapClickableTableRow($table);
            //$row->addYesNo($notificationRow->archive);
            //$row->addText($notificationRow->content->contentType->contentType);

            if ($notificationRow->read) {
                $row->addText($notificationRow->subject);
                $row->addText($notificationRow->message);
                $row->addText($notificationRow->content->dateTime->getShortDateTimeWithSecondLeadingZeroFormat());
            } else {
                $row->addBoldText($notificationRow->subject);
                $row->addBoldText($notificationRow->message);
                $row->addBoldText($notificationRow->content->dateTime->getShortDateTimeWithSecondLeadingZeroFormat());
            }


            //$contentType = $notificationRow->content->getContentType();
            //  $row->addText($contentType->getSubject());
            //  $row->addText($contentType->getMessage());*/


            //  $row->addText($notificationRow->to->displayName);

            $site = clone(ArchiveSite::$site);
            $site->addParameter(new NotificationParameter($notificationRow->id));
            $row->addIconSite($site);

            $site = clone(RedirectSite::$site);
            $site->addParameter(new NotificationParameter($notificationRow->id));
            $row->addClickableSite($site);

            //$row->addClickableSite($contentType->getViewSite());

        }

        $pagination = new BootstrapPagination($this);
        $pagination->paginationReader = $notificationReader;



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}