<?php


namespace Nemundo\Process\App\Podcast\Content\Episode;


use Nemundo\Process\Content\View\AbstractContentView;

class EpisodeContentView extends AbstractContentView
{

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}