<?php


namespace Nemundo\Process\Template\Content\Assignment;


use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Group\Com\GroupListBox;
use Nemundo\Process\Group\Com\ListBox\GroupTypeListBox;
use Nemundo\Process\Workflow\Content\Form\AbstractStatusForm;

class GroupAssignmentForm extends AbstractStatusForm
{

    /**
     * @var GroupTypeListBox
     */
    private $groupType;

    /**
     * @var GroupListBox
     */
    private $group;

    public function getContent()
    {

        $this->groupType=new GroupTypeListBox($this);


$this->group= new GroupListBox($this);
$this->group->validation=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.

        $item=new GroupAssignmentItem();
        $item->parentId=$this->parentId;
        $item->groupId =$this->group->getValue();
        $item->saveItem();

    }


}