<?php


namespace Nemundo\Process\Template\Content\Assignment;


use Nemundo\Process\Group\Com\GroupListBox;
use Nemundo\Process\Group\Com\ListBox\GroupTypeListBox;
use Nemundo\Process\Workflow\Content\Form\AbstractStatusForm;

class GroupAssignmentForm extends AbstractStatusForm
{

    /**
     * @var GroupTypeListBox
     */
    private $groupType;

    /**
     * @var GroupListBox
     */
    private $group;

    public function getContent()
    {

        //$this->groupType = new GroupTypeListBox($this);

        $this->group = new GroupListBox($this);

        $this->group->validation = true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $status = new GroupAssignmentStatus();
        $status->parentId = $this->parentId;
        $status->groupId = $this->group->getValue();
        $status->saveType();

    }


}