<?php


namespace Nemundo\Process\App\Favorite\Icon;


use Nemundo\Package\FontAwesome\AbstractFontAwesomeIcon;

class EmptyFavoriteIcon extends AbstractFontAwesomeIcon
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub
    }

}