<?php

namespace Nemundo\Process\Template\Status\WorkflowRestore;

use Nemundo\Core\Language\LanguageCode;
use Nemundo\Core\Language\Translation;
use Nemundo\Process\Workflow\Content\Status\AbstractProcessStatus;

class WorkflowRestoreStatus extends AbstractProcessStatus
{

    protected function loadContentType()
    {
        $this->typeLabel = 'Wiederherstellen';
        $this->typeId = '09b8817a-926b-4c7c-8c11-2a2a4f77c1f6';
        //$this->closeWorkflow = true;
    }


    /*
    protected function onCreate()
    {

        //$process = $this->getParentProcess();
        //$process->cancelAssignment();
        //$process->setActive();

    }*/


    /*
    public function getSubject()
    {

        $subject[LanguageCode::EN] = 'Workflow was deleted';
        $subject[LanguageCode::DE] = 'Workflow wurde gelöscht';

        return (new Translation())->getText($subject);

    }*/


    public function getMessage()
    {

        $subject[LanguageCode::EN] = 'Workflow was restored';
        $subject[LanguageCode::DE] = 'Workflow wurde wiederhergestellt';

        return (new Translation())->getText($subject);

        //return parent::getMessage(); // TODO: Change the autogenerated stub
    }


}