<?php


namespace Nemundo\Process\Geo\Item;


use Nemundo\Core\Type\Geo\GeoCoordinate;
use Nemundo\Process\Content\Item\AbstractContentItem;
use Nemundo\Process\Geo\Data\Geo\Geo;

abstract class AbstractGeoContentItem extends AbstractContentItem
{

    /**
     * @var GeoCoordinate
     */
    public $coordinate;


    public function __construct($id = null)
    {
        parent::__construct($id);
        $this->coordinate = new GeoCoordinate();
    }

    public function saveItem()
    {
        parent::saveItem(); // TODO: Change the autogenerated stub


        //check for coordinate

        $this->saveGeo();

    }


    private function saveGeo()
    {

        $data = new Geo();
        $data->id = $this->dataId;
        $data->coordinate = $this->coordinate;
        $data->save();


    }


}