<?php


namespace Nemundo\Process\Template\Content\Text;


use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

class TextContentForm extends AbstractContentForm
{

    /**
     * @var TextContentType
     */
    public $contentType;

    /**
     * @var BootstrapTextBox
     */
    private $text;

    public function getContent()
    {


        //$p=new Paragraph($this);
        //$p->content='dataid: '.$this->dataId;

        $this->text=new BootstrapTextBox($this);
        $this->text->label='Text';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {
        $textRow=$this->contentType->getDataRow();
        $this->text->value=$textRow->text;

    }


    protected function onSubmit()
    {

        $type=new TextContentType($this->dataId);
        $type->parentId=$this->parentId;
        $type->text=$this->text->getValue();
        $type->saveType();

    }

}