<?php


namespace Nemundo\Process\App\Notification\Content\Message;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\User\Com\ListBox\UserListBox;

class MessageNotificationContentForm extends AbstractContentForm
{

    /**
     * @var UserListBox
     */
    private $to;

    /**
     * @var BootstrapLargeTextBox
     */
    private $message;


    public function getContent()
    {

        $this->to=new UserListBox($this);
        $this->to->label='To';
        $this->to->validation=true;

        $this->message=new BootstrapLargeTextBox($this);
        $this->message->label='Message';


        $this->to->emptyValueAsDefault=false;
        $this->message->value = '123123123';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $type=new MessageNotificationContentType();
        $type->parentId=$this->parentId;
        $type->userToId=$this->to->getValue();
        $type->message = $this->message->getValue();
$type->saveType();

        // TODO: Implement onSubmit() method.
    }

}