<?php


namespace Nemundo\Process\App\Survey\Com;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Process\Content\Parameter\ContentTypeParameter;
use Nemundo\Process\Content\Type\AbstractContentType;
use Nemundo\Process\Content\Type\AbstractMenuContentType;
use Nemundo\Process\Workflow\Content\Status\AbstractProcessStatus;


// SequenceMenu
class NextMenu extends AbstractHtmlContainer
{

    /**
     * @var AbstractContentType
     */
    public $contentType;

    /**
     * @var AdminTable
     */
    private $table;

    public function getContent()
    {

        $this->table=new AdminTable($this);
        $this->addNextMenu($this->contentType);

     /*   protected function addNextStatusMenu(AbstractProcessStatus $status = null)
    {

        if ($status !== null) {
            //$this->addStatusLabel($status);
            $this->addLabel($status);
            $this->addNextStatusMenu($status->getNextStatus());
        }

    }*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function addNextMenu(AbstractMenuContentType $status = null)
    {

        if ($status !== null) {

            $row = new TableRow($this->table);


            if ($status->id == (new ContentTypeParameter())->getValue()) {
            $row->addBoldText($status->type);
                } else {
                $row->addText($status->type);
            }

            //$this->addStatusLabel($status);
            //$this->addLabel($status);
            $this->addNextMenu($status->getNextMenu());
        }

    }



}