<?php


namespace Nemundo\Process\Group\Com\Hyperlink;


use Nemundo\Com\Html\Hyperlink\SiteHyperlink;
use Nemundo\Process\Group\Parameter\GroupParameter;
use Nemundo\Process\Group\Site\GroupContentViewSite;

class GroupContentViewHyperlink extends SiteHyperlink
{

    public $groupId;

    public function getContent()
    {

        $site = clone(GroupContentViewSite::$site);
        $site->addParameter(new GroupParameter($this->groupId));

        $this->site = $site;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


}