<?php


namespace Nemundo\Process\Content\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Content\Data\ContentType\ContentTypeReader;
use Nemundo\Process\Content\Parameter\ContentTypeParameter;
use Nemundo\Process\Content\Type\AbstractContentTypeCollection;

class ContentTypeCollectionListBox extends BootstrapListBox
{

    /**
     * @var AbstractContentTypeCollection
     */
    public $contentTypeCollection;


    protected function loadContainer()
    {

        $this->label = 'Content Type';
        $this->name = (new ContentTypeParameter())->parameterName;

        /*
            $reader = new ContentTypeReader();
        $reader->addOrder($reader->model->contentType);
        foreach ($reader->getData() as $contentTypeRow) {
            $this->addItem($contentTypeRow->id, $contentTypeRow->contentType);
        }*/

    }


    public function getContent()
    {

        foreach ($this->contentTypeCollection->getContentTypeList() as $contentType) {
            $this->addItem($contentType->typeId,$contentType->typeLabel);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}