<?php


namespace Nemundo\Process\Template\Content\LargeText;


use Nemundo\Process\Content\Type\AbstractTreeContentType;
use Nemundo\Process\Template\Data\LargeText\LargeText;


class LargeTextContentType extends AbstractLargeTextContentType  // AbstractTreeContentType
{

    public $largeText;


    protected function loadContentType()
    {

        $this->typeId = '1b4e6652-8f85-4cd8-b44a-1f50afb696ac';
        $this->typeLabel = 'Large Text';

        $this->formClass = LargeTextContentForm::class;
        $this->viewClass = LargeTextContentView::class;


    }


    /*
    protected function onCreate()
    {

        $data = new LargeText();
        //$data->updateOnDuplicate = true;
        $data->largeText = $this->largeText;
      $this->dataId =   $data->save();

        //$this->addSearchText($this->largeText);

    }


    protected function onUpdate()
    {
        parent::onUpdate(); // TODO: Change the autogenerated stub
    }*/


}