<?php


namespace Nemundo\Process\Template\Content\EventAdd;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Writer\TreeWriter;
use Nemundo\Process\Template\Data\Event\EventReader;

class EventAddForm extends AbstractContentForm
{

    /**
     * @var BootstrapListBox
     */
    private $event;

    public function getContent()
    {

        $this->event=new BootstrapListBox($this);

        $reader=new EventReader();
        foreach ($reader->getData() as $eventRow) {
            $this->event->addItem($eventRow->id,$eventRow->event);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.

        $writer=new TreeWriter();
        $writer->parentId=$this->parentId;
        $writer->dataId=$this->event->getValue();
        $writer->write();


    }

}