<?php


namespace Nemundo\Process\Template\Item;


use Nemundo\Process\Content\Item\AbstractContentItem;
use Nemundo\Process\Template\Data\LargeText\LargeText;
use Nemundo\Process\Template\Type\LargeTextContentType;

class LargeTextContentItem extends AbstractContentItem
{

    public $largeText;


    protected function loadItem()
    {
        //parent::loadItem(); // TODO: Change the autogenerated stub
        $this->contentType = new LargeTextContentType();
    }

    public function saveData()
    {

       // $this->contentType = new LargeTextContentType();

        $data = new LargeText();
        $data->updateOnDuplicate=true;
        $data->id = $this->dataId;
        $data->largeText = $this->largeText;
        $data->save();

        $this->addSearchText($this->largeText);

     //   $this->saveContent();

    }

}