<?php


namespace Nemundo\Process\Template\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Template\Data\LargeText\LargeTextReader;
use Nemundo\Process\Template\Item\LargeTextContentItem;

abstract class AbstractLargeTextContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $largeText;


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub
        $this->largeText = new BootstrapLargeTextBox($this);
        $this->largeText->label = 'Large Text';

    }

    /*public function getContent()
    {

        $this->largeText = new BootstrapLargeTextBox($this);
        $this->largeText->label = 'Large Text';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }*/


    protected function loadUpdateForm()
    {

        $row = (new LargeTextReader())->getRowById($this->dataId);
        $this->largeText->value = $row->largeText;

        //(new Debug())->write($row->largeText);
        //exit;

    }



    /*
    protected function onSubmit()
    {

        $item = new LargeTextContentItem($this->dataId);
        $item->parentId = $this->parentId;
        $item->largeText = $this->largeText->getValue();
        $item->saveItem();

    }*/


}