<?php


namespace Nemundo\Process\Template\Form;


use Nemundo\Core\Language\LanguageCode;
use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Template\Item\CancelContentItem;
use Nemundo\Process\Template\Status\CancelStatus;
use Nemundo\Process\Workflow\Content\Form\AbstractStatusForm;
use Nemundo\Process\Template\Item\CommentItem;

class CancelStatusForm extends AbstractStatusForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $comment;

    public function getContent()
    {

        $this->comment = new BootstrapLargeTextBox($this);
        $this->comment->label[LanguageCode::EN] = 'Comment';
        $this->comment->label[LanguageCode::DE] = 'Kommentar (Abbruch)';


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $item = new CancelStatus();
        $item->parentId = $this->parentId;
        $item->comment = $this->comment->getValue();
        $item->saveType();

    }


}