<?php


namespace Nemundo\Process\Template\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Form\AbstractStatusForm;
use Nemundo\Process\Template\Data\LargeText\LargeText;

class CommentForm extends AbstractStatusForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $comment;

    public function getContent()
    {

        $this->comment=new BootstrapLargeTextBox($this);
        $this->comment->label = 'Comment';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSave()
    {


        $data = new LargeText();
        $data->largeText=$this->comment->getValue();
      $this->dataId=  $data->save();


      $this->saveWorkflowLog();


    }


}