<?php


namespace Nemundo\Process\Template\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapFileUpload;
use Nemundo\Process\Form\AbstractContentForm;
use Nemundo\Process\Form\AbstractStatusForm;
use Nemundo\Process\Template\Builder\DocumentStatusBuilder;
use Nemundo\Process\Template\Data\Document\Document;
use Nemundo\Process\Template\Item\DocumentContentItem;

class DocumentContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapFileUpload
     */
    private $document;

    public function getContent()
    {

        $this->document = new BootstrapFileUpload($this);
        $this->document->label = 'Document';
        $this->document->multiUpload = true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        foreach ($this->document->getMultiFileRequest() as $fileRequest) {


            $builder = new DocumentContentItem();
            $builder->fileRequest = $fileRequest;
            $builder->parentId=$this->parentId;
            $builder->saveItem();


           /*
            $data = new Document();
            $data->active = true;
            $data->document->fromFileRequest($fileRequest);
            $data->workflowId = $this->workflowId;
            $this->dataId = $data->save();

            $this->saveWorkflowLog();*/

        }


    }

}