<?php


namespace Nemundo\Process\Template\Form;



use Nemundo\Package\Bootstrap\FormElement\BootstrapFileUpload;
use Nemundo\Process\Form\AbstractStatusForm;
use Nemundo\Process\Item\WorkflowItem;
use Nemundo\Process\Template\Data\Document\Document;

class DocumentForm extends AbstractStatusForm
{

    /**
     * @var BootstrapFileUpload
     */
    private $document;

    public function getContent()
    {

        $this->document=new BootstrapFileUpload($this);
        $this->document->label = 'Document';
        $this->document->multiUpload=true;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSave()
    {

        foreach ($this->document->getMultiFileRequest() as $fileRequest) {

        $data = new Document();
        $data->active=true;
        $data->document->fromFileRequest($fileRequest);
        $data->workflowId = $this->workflowId;
      $this->dataId=  $data->save();

        $this->saveWorkflowLog();

        }


    }

}