<?php


namespace Nemundo\Process\Template\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\Form\AbstractContentForm;
use Nemundo\Process\Template\Data\LargeText\LargeTextReader;
use Nemundo\Process\Template\Item\LargeTextContentItem;

class LargeTextContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $comment;

    public function getContent()
    {

        $this->comment = new BootstrapLargeTextBox($this);
        $this->comment->label = 'Large Text';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $row = (new LargeTextReader())->getRowById($this->dataId);
        $this->comment->value = $row->largeText;

        //(new Debug())->write($row->largeText);
        //exit;

    }


    protected function onSubmit()
    {

        $item = new LargeTextContentItem($this->dataId);
        $item->parentId = $this->parentId;
        $item->largeText = $this->comment->getValue();
        $item->saveItem();

    }


}