<?php


namespace Nemundo\Process\Content\Form;


use Nemundo\Html\Paragraph\Paragraph;

class ContentForm extends AbstractContentForm
{


    public function getContent()
    {

        $p = new Paragraph($this);
        $p->content = 'Content Form';


        $p = new Paragraph($this);
        $p->content = 'Content Type '.$this->contentType->typeLabel;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {


        $this->contentType->parentId=$this->parentId;
        $this->contentType->saveType();


        /*
        $item = new ContentItem($this->dataId);
        $item->contentType = $this->contentType;
        $item->dataId = $this->dataId;
        $item->parentId = $this->parentId;
        $item->saveItem();*/

    }

}