<?php


namespace Nemundo\Process\Relation\Com;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\Relation\Data\Relation\RelationReader;

class RelationTable extends AdminClickableTable
{

    public $contentId;

    public function getContent()
    {

        $header=new TableHeader($this);
        $header->addText('Relation');

        $reader = new RelationReader();
        $reader->model->loadTo();
        $reader->filter->andEqual($reader->model->fromId,$this->contentId);
        foreach ($reader->getData() as $relationRow) {
            $row=new BootstrapClickableTableRow($this);
            $row->addText($relationRow->to->subject);
        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}