<?php


namespace Nemundo\Process\Content\Reader;


use Nemundo\Core\Debug\Debug;
use Nemundo\Model\Join\ModelJoin;
use Nemundo\Process\Content\Data\Content\ContentReader;
use Nemundo\Process\Content\Data\Tree\TreeModel;

// ContentJoinTreeReader
class ContentTreeReader extends ContentReader
{

    public $parentId;


    protected function loadData()
    {

        $treeModel = new TreeModel();
        $join = new ModelJoin($this);
        $join->externalModel = $treeModel;
        $join->externalType = $treeModel->parentId;
        $join->type = $this->model->id;

        //(new Debug())->write($this->parentId);

        if ($this->parentId !== null) {
            //(new Debug())->write($this->parentId);
            $this->filter->andEqual($treeModel->childId, $this->parentId);
        }

        parent::loadData(); // TODO: Change the autogenerated stub

    }


}