<?php


namespace Nemundo\Process\Template\Content\YesNo;


use Nemundo\Package\Bootstrap\FormElement\BootstrapCheckBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

abstract class AbstractYesNoContentForm extends AbstractContentForm
{

    /**
     * @var AbstractYesNoContentType
     */
    public $contentType;

    /**
     * @var BootstrapCheckBox
     */
    protected $checkbox;


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->checkbox = new BootstrapCheckBox($this);
        $this->checkbox->label = 'test';

    }

    public function getContent()
    {



        //$this->checkbox->autofocus = true;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $this->contentType->yesNo=$this->checkbox->getValue();
        $this->contentType->saveType();

    }


}