<?php


namespace Nemundo\Process\Template\YesNo;


use Nemundo\Package\Bootstrap\FormElement\BootstrapCheckBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

abstract class AbstractYesNoContentForm extends AbstractContentForm
{

    /**
     * @var BootstrapCheckBox
     */
    protected $checkbox;


    public function getContent()
    {


        $this->checkbox = new BootstrapCheckBox($this);
        $this->checkbox->label = '';
        $this->checkbox->autofocus = true;


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}