<?php


namespace Nemundo\Process\Template\Content\YesNo;


use Nemundo\Package\FontAwesome\Icon\CheckIcon;
use Nemundo\Process\Content\View\AbstractContentView;
use Nemundo\Process\Template\Content\YesNo\AbstractYesNoContentType;

class YesNoContentView extends AbstractContentView
{
    /**
     * @var AbstractYesNoContentType
     */
    public $contentType;

    public function getContent()
    {

        $row = $this->contentType->getDataRow();
        if ($row->yesNo) {
            new CheckIcon($this);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}