<?php


namespace Nemundo\Process\Template\Content\Url;


use Nemundo\Process\Content\Type\AbstractTreeContentType;
use Nemundo\Process\Template\Content\Text\AbstractTextContentType;

abstract class AbstractUrlContentType extends AbstractTextContentType
{

   // public $url;


    public function __construct($dataId = null)
    {

        parent::__construct($dataId);
        $this->typeLabel='Url';
        $this->viewClass=UrlContentView::class;
    }



    /*
    protected function onCreate()
    {
        $this->text = $this->url;
        parent::onCreate(); // TODO: Change the autogenerated stub
    }*/

}