<?php


namespace Nemundo\Process\Template\Content\Url;


use Nemundo\Process\Content\Type\AbstractTreeContentType;
use Nemundo\Process\Template\Content\Text\AbstractTextContentType;

abstract class AbstractUrlContentType extends AbstractTextContentType
{

    public $url;


    public function __construct($dataId = null)
    {
        parent::__construct($dataId);
        $this->typeLabel='Url';
        $this->viewClass=UrlContentView::class;
    }

   /* protected function loadContentType()
    {

        $this->typeId='bffc3e3f-7a32-4d56-821d-aaf5a2a0c8b5';



        // TODO: Implement loadContentType() method.
    }*/


    protected function onCreate()
    {
        $this->text = $this->url;
        parent::onCreate(); // TODO: Change the autogenerated stub
    }

}