<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Package\Bootstrap\FormElement\BootstrapLargeTextBox;
use Nemundo\Process\App\Survey\Data\Survey\SurveyReader;
use Nemundo\Process\App\Survey\Data\Survey\SurveyUpdate;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Form\AbstractSequenceForm;

class DescriptionContentForm extends AbstractSequenceForm
{

    /**
     * @var BootstrapLargeTextBox
     */
    private $description;

    public function getContent()
    {

        $this->description=new BootstrapLargeTextBox($this);


        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function loadUpdateForm()
    {

        $reader = new SurveyReader();

    }

    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.

        $update=new SurveyUpdate();
        $update->beschreibung=$this->description->getValue();
        $update->updateById($this->parentId);

    }

}