<?php


namespace Nemundo\Process\App\Survey\Content\Form;


use Nemundo\Html\Container\AbstractContentContainer;
use Nemundo\Html\Paragraph\Paragraph;
use Nemundo\Process\App\Survey\Data\Survey\SurveyReader;
use Nemundo\Process\Content\Form\AbstractContentActionPanel;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Form\AbstractSequenceForm;

class OptionTextContentForm extends AbstractSequenceForm  // AbstractContentActionPanel
{


    public function getContent()
    {

        $p=new Paragraph($this);
        $p->content='Opteion TExt'.$this->parentId;


        /*
        $row=(new SurveyReader())->getRowById($this->parentId);
        $p=new Paragraph($this);
        $p->content= $row->vorname;
*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {
        // TODO: Implement onSubmit() method.



    }

}