<?php


namespace Nemundo\Process\App\Task\Com\ListBox;


use Nemundo\Package\Bootstrap\FormElement\BootstrapListBox;
use Nemundo\Process\App\Task\Data\TaskType\TaskTypeReader;
use Nemundo\Process\App\Task\Parameter\TaskTypeParameter;

class TaskTypeListBox extends BootstrapListBox
{


    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->name=(new TaskTypeParameter())->getParameterName();
        $this->label='Task Type';

    }

    public function getContent()
    {

        $reader = new TaskTypeReader();
        $reader->model->loadTaskType();
        foreach ($reader->getData() as $taskTypeRow) {
            $this->addItem($taskTypeRow->id,$taskTypeRow->taskType->contentType);
        }

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}