<?php


namespace Nemundo\Process\Content\Collection;


use Nemundo\Process\Content\Type\AbstractContentType;

class ContentTypeCollection extends AbstractContentTypeCollection
{

 protected function loadCollection()
    {
        // TODO: Implement loadCollection() method.
    }


    public function addContentType(AbstractContentType $contentType)
    {
        return parent::addContentType($contentType); // TODO: Change the autogenerated stub
    }


}