<?php


namespace Nemundo\Process\App\Feed\Content\Feed;


use Nemundo\Package\Bootstrap\FormElement\BootstrapTextBox;
use Nemundo\Process\Content\Form\AbstractContentForm;

class FeedContentForm extends AbstractContentForm
{

    /**
     * @var FeedContentType
     */
    public $contentType;

    /**
     * @var BootstrapTextBox
     */
    private $rssUrl;

    public function getContent()
    {

        $this->rssUrl=new BootstrapTextBox($this);
        $this->rssUrl->label='RSS Url';

        return parent::getContent(); // TODO: Change the autogenerated stub
    }


    protected function onSubmit()
    {

        $this->contentType->feedUrl = $this->rssUrl->getValue();
        $this->contentType->saveType();


    }


}