<?php


namespace Nemundo\Process\Group\Type;


use Nemundo\User\Data\Usergroup\UsergroupReader;

class UsergroupGroupType extends AbstractGroupContentType
{
    protected function loadContentType()
    {

        $this->typeLabel = 'Usergroup (Content Group)';
        $this->typeId = 'fb0d7de7-8438-43a9-8d22-eec213fb23e5';

    }


    protected function onCreate()
    {
        parent::onCreate(); // TODO: Change the autogenerated stub

        // usergroup setup???

    }

    protected function getGroupLabel()
    {
        return (new UsergroupReader())->getRowById($this->dataId)->usergroup;
        }




}