<?php


namespace Nemundo\Process\Group\Content\Add;


use Nemundo\Process\Content\Data\ContentGroup\ContentGroup;
use Nemundo\Process\Content\Item\AbstractContentItem;
use Nemundo\Process\Content\Item\ContentItem;
use Nemundo\Process\Group\Content\GroupContentItem;
use Nemundo\User\Type\UserSessionType;

class AddGroupContentItem extends AbstractContentItem
{

    public $groupId;

    public function getSubject()
    {
        //return parent::getSubject(); // TODO: Change the autogenerated stub

        $subject='asdf';
        return $subject;


    }


    protected function saveData()
    {

        $this->contentType = new AddGroupContentType();




        if ($this->groupId == null) {
            $groupItem = new GroupContentItem();
            $groupItem->group = 'for to do xy';
            $groupItem->saveItem();
            $groupItem->addUser((new UserSessionType())->userId);
            $this->groupId = $groupItem->dataId;
        }




        $data = new ContentGroup();
        $data->ignoreIfExists = true;
        $data->contentId = $this->parentId;
        $data->groupId = $this->groupId;  //group->getValue();
        $data->save();

/*
        $item = new ContentItem();
        $item->contentType = new AddGroupContentType();
        $item->parentId = $this->parentId;
        $item->dataId = $this->groupId;  // $this->group->getValue();
        $item->saveItem();*/

        // TODO: Implement saveItem() method.
    }
}