<?php


namespace Nemundo\Process\Group\Content\Add;


use Nemundo\Process\Content\Data\ContentGroup\ContentGroup;
use Nemundo\Process\Content\Form\AbstractContentForm;
use Nemundo\Process\Content\Item\ContentItem;
use Nemundo\Process\Group\Com\GroupListBox;

class AddGroupContentForm extends AbstractContentForm
{

    /**
     * @var GroupListBox
     */
    private $group;

    public function getContent()
    {
        $this->group=new GroupListBox($this);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }
    protected function onSubmit()
    {

        $item = new AddGroupContentItem();
        $item->parentId=$this->parentId;
        $item->groupId = $this->group->getValue();
        $item->saveItem();

        /*
        $data = new ContentGroup();
        $data->ignoreIfExists=true;
        $data->contentId = $this->parentId;
        $data->groupId = $this->group->getValue();
        $data->save();


        $item = new ContentItem();
        $item->contentType=new AddGroupContentType();
        $item->parentId=$this->parentId;
        $item->dataId=$this->group->getValue();
        $item->saveItem();*/

        // TODO: Implement onSubmit() method.
    }
}