<?php


namespace Nemundo\Process\Group\Content\Add;


use Nemundo\Process\Content\Item\AbstractContentItem;

class AddGroupContentItem extends AbstractContentItem
{
public function getSubject()
{
    return parent::getSubject(); // TODO: Change the autogenerated stub
}
public function saveItem()
{
    // TODO: Implement saveItem() method.
}
}