<?php


namespace Nemundo\Process\Com\Menu;


use Nemundo\Admin\Com\Table\AdminTable;
use Nemundo\Com\Html\Hyperlink\SiteHyperlink;
use Nemundo\Com\TableBuilder\TableRow;
use Nemundo\Package\FontAwesome\Icon\ArrowRightIcon;
use Nemundo\Package\FontAwesome\Icon\CheckIcon;
use Nemundo\Process\Item\WorkflowItem;
use Nemundo\Process\Parameter\StatusParameter;
use Nemundo\Process\Process\AbstractProcess;
use Nemundo\Process\Status\AbstractStatus;

class HistoryProcessMenu extends AbstractProcessMenu
{


    public function getContent()
    {


        //$table = new AdminTable($this);

        $item = new WorkflowItem($this->workflowId);

        foreach ($item->getWorkflowLog() as $logRow) {

            $row = new TableRow($this->table);
            new CheckIcon($row);

            $row->addText($logRow->status->statusLabel);

            $text = $logRow->user->displayName.' '.$logRow->dateTime->getShortDateFormat();
            $row->addText($text);


        }


        $row = new TableRow($this->table);
        new ArrowRightIcon($row);
        $row->addText($this->formStatus->label);
        $row->addEmpty();


        $this->addStatusSite($this->workflowStatus->getNextStatus());



        //$row->addEmpty();



        //$nextStatus = $this->workflowStatus->getNextStatus();









        return parent::getContent(); // TODO: Change the autogenerated stub
    }





}