<?php


namespace Nemundo\Process\Com\Menu;


class ProcessMenu extends AbstractProcessMenu
{

    public function getContent()
    {


        $workflowStatusFound = false;
        $nextStatus = $this->workflowStatus->getNextStatus();

        foreach ($this->process->getProcessStatusList() as $status) {


            if ($workflowStatusFound) {
                $this->addStatusLabel($status);
            } else {
                $this->addStatusSite($status);
            }

            if ($nextStatus !== null) {
                if ($nextStatus->id == $status->id) {
                    $this->addSubmenu($status);
                    $workflowStatusFound = true;
                }
            }





        }


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}