<?php


namespace Nemundo\Process\Template\Content\Date;


use Nemundo\Package\Bootstrap\FormElement\BootstrapDatePicker;
use Nemundo\Process\Content\Form\AbstractContentForm;

abstract class AbstractDateContentForm extends AbstractContentForm
{

    /**
     * @var AbstractDateContentType
     */
    public $contentType;

    /**
     * @var BootstrapDatePicker
     */
    protected $date;

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $this->date = new BootstrapDatePicker($this);
        $this->date->label = 'Date';

    }

    /*
    public function getContent()
    {


        $this->date = new BootstrapDatePicker($this);
        $this->date->label = '';

        // kein Autofocus setzen !!!


        return parent::getContent(); // TODO: Change the autogenerated stub
    }*/


    protected function onSubmit()
    {

$this->contentType->date->fromGermanFormat($this->date->getValue());
$this->contentType->saveType();

        // TODO: Implement onSubmit() method.
    }

}