<?php


namespace Nemundo\Process\Workflow\Content\Status;

use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Process\Content\Type\AbstractContentType;
use Nemundo\Process\Workflow\Content\Form\AbstractStatusForm;

abstract class AbstractProcessStatus extends AbstractContentType
{

    use ProcessStatusTrait;


    /*
    public function getViewSite($dataId)
    {

        $item = $this->getItem($dataId);
        $parentId = $item->getParentId();
        $site = $item->getParentContentType()->getViewSite($parentId);

        return $site;

    }*/

    /**
     * @param AbstractHtmlContainer $parent
     * @return AbstractStatusForm
     */
    public function getForm(AbstractHtmlContainer $parent)
    {
        return parent::getForm($parent); // TODO: Change the autogenerated stub
    }

}