<?php


namespace Nemundo\Process\App\Calendar\Com\Container;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Com\TableBuilder\TableHeader;
use Nemundo\Core\Type\DateTime\Date;
use Nemundo\Html\Block\Div;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\App\Calendar\Data\CalendarIndex\CalendarIndexPaginationReader;
use Nemundo\Process\Config\ProcessConfig;

class CalendarContainer extends AbstractHtmlContainer
{

    public function getContent()
    {

        $reader = new CalendarIndexPaginationReader();
        $reader->model->loadContent();
        $reader->model->content->loadContentType();

        $reader->filter->andEqualOrGreater($reader->model->date, (new Date())->setNow()->getIsoDateFormat());

        $reader->addOrder($reader->model->date);
        $reader->paginationLimit = ProcessConfig::PAGINATION_LIMIT;

        $table = new AdminClickableTable($page);

        $div = new Div($page);

        $header = new TableHeader($table);
        $header->addText($reader->model->date->label);
        $header->addText($reader->model->title->label);
        $header->addText('View');
        $header->addText('Type');
        $header->addText('Source');
        $header->addText('Source Type');

        foreach ($reader->getData() as $calendarIndexRow) {

            $row = new BootstrapClickableTableRow($table);
            $row->addText($calendarIndexRow->date->getShortDateLeadingZeroFormat());
            $row->addText($calendarIndexRow->title);


            $row->addText($calendarIndexRow->content->contentType->contentType);

            $type = $calendarIndexRow->content->getContentType();
            $type->getView($row);

            $row->addText($type->typeLabel);

            $row->addClickableSite($type->getViewSite());

        }


        $pagination = new BootstrapPagination($page);
        $pagination->paginationReader = $reader;



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}