<?php


namespace Nemundo\Process\Com\Button;


use Nemundo\Admin\Com\Button\AdminSiteButton;
use Nemundo\Process\Workflow\Parameter\StatusParameter;
use Nemundo\Process\Status\AbstractStatus;
use Nemundo\Process\Template\Status\ReopenStatus;
use Nemundo\Web\Site\Site;

class ReopenStatusButton extends AdminSiteButton
{

    /**
     * @var AbstractStatus
     */
    public $status;

    public function getContent()
    {

        $this->status = new ReopenStatus();

        //if ($this->status !== null) {
        $this->content = $this->status->label;
        $this->site=new Site();
        $this->site->addParameter(new StatusParameter($this->status->id));
        /*} else {
            $this->disabled=true;
        }*/

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}