<?php


namespace Nemundo\Process\Workflow\Com\Table;


use Nemundo\Admin\Com\Table\AdminLabelValueTable;

class WorkflowInfoTable extends AdminLabelValueTable
{

    public function getContent()
    {



        /*
        $table = new AdminLabelValueTable($layout->col3);
        $table->addLabelValue($workflowRow->model->workflowNumber->label, $workflowRow->workflowNumber);
        $table->addLabelValue($workflowRow->model->subject->label, $workflowRow->subject);
        //$table->addLabelValue($model->assignment->label, $workflowRow->assignment->getValue());
        $table->addLabelValue($workflowRow->model->assignment->label, $workflowRow->assignment->group);

        $table->addLabelValue($workflowRow->model->assignment->groupType->label, $workflowRow->assignment->groupType->contentType);

        $ul = new UnorderedList();

        $group = new GroupContentType($workflowRow->assignmentId);
        foreach ($group->getUserList() as $userRow) {
            $ul->addText($userRow->login);
        }
        $table->addLabelCom('Member', $ul);

        $table->addLabelValue($workflowRow->model->status->label, $workflowRow->status->contentType);
        $table->addLabelYesNoValue($workflowRow->model->workflowClosed->label, $workflowRow->workflowClosed);


        if ($workflowRow->deadline !== null) {
            $table->addLabelValue($workflowRow->model->deadline->label, $workflowRow->deadline->getShortDateLeadingZeroFormat());
        }

        $table->addLabelValue($workflowRow->model->dateTime->label, $workflowRow->dateTime->getShortDateTimeLeadingZeroFormat());
        $table->addLabelValue($workflowRow->model->user->label, $workflowRow->user->displayName);
*/


        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}