<?php


namespace Nemundo\Process\App\Feed\Widget;


use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\Db\Sql\Order\SortOrder;
use Nemundo\Package\Bootstrap\Pagination\BootstrapPagination;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;
use Nemundo\Process\App\Feed\Content\Item\FeedItemContentType;
use Nemundo\Process\App\Feed\Data\FeedItem\FeedItemPaginationReader;
use Nemundo\Process\Config\ProcessConfig;

class FeedWidget extends AdminWidget
{

    public function getContent()
    {


        $this->widgetTitle='Feed';

        $table = new AdminClickableTable($this);

        $itemReader = new FeedItemPaginationReader();
        $itemReader->model->loadFeed();
        $itemReader->addOrder($itemReader->model->dateTime,SortOrder::DESCENDING);
        $itemReader->paginationLimit = ProcessConfig::PAGINATION_LIMIT;
        foreach ($itemReader->getData() as $itemRow) {

            $row = new BootstrapClickableTableRow($table);
            $row->addText($itemRow->title);
            $row->addText($itemRow->description);
            $row->addText($itemRow->dateTime->getShortDateTimeLeadingZeroFormat());
            $row->addText($itemRow->feed->title);

            $contentType = new FeedItemContentType($itemRow->id);
            $row->addClickableSite($contentType->getViewSite());

        }


        //$pagination = new BootstrapPagination($layout->col2);
        //$pagination->paginationReader = $itemReader;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}